version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - social-kit-network

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092" # For external access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - social-kit-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: social_kit
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - social-kit-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - social-kit-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - social-kit-network
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - social-kit-network

  api-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: api-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/social_kit
      MONGO_URI: mongodb://mongodb:27017/social_kit
      KAFKA_BROKER: kafka:9092
      JWT_SECRET: "PAVAROTI"
    depends_on:
      - mysql
      - mongodb
      - kafka
    networks:
      - social-kit-network

  api-backoffice:
    build:
      context: ./apps/backoffice-backend
      dockerfile: Dockerfile
    container_name: api-backoffice-backend
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/social_kit
      MONGO_URI: mongodb://mongodb:27017/social_kit
      KAFKA_BROKER: kafka:9092
      JWT_SECRET: "PAVAROTI"
    depends_on:
      - mysql
      - mongodb
      - kafka
    networks:
      - social-kit-network

  publish-service:
    build:
      context: ./apps/publish-service
      dockerfile: Dockerfile
    container_name: publish-service
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/social_kit
      MONGO_URI: mongodb://mongodb:27017/social_kit
      KAFKA_BROKER: kafka:9092
    depends_on:
      - mysql
      - mongodb
      - kafka
    networks:
      - social-kit-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
    depends_on:
      - api-backend
    networks:
      - social-kit-network

  backoffice-frontend:
    build:
      context: ./apps/backoffice-frontend
      dockerfile: Dockerfile
    container_name: backoffice-frontend
    ports:
      - "4174:4173"
    depends_on:
      - api-backoffice
    networks:
      - social-kit-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9999:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - social-kit-network

  mailpit:
    image: mailhog/mailhog:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - social-kit-network

  namshi-smtp:
    image: namshi/smtp:latest
    container_name: namshi-smtp
    ports:
      - "2525:25"
    networks:
      - social-kit-network

volumes:
  mysql-data:
  mongodb-data:
  grafana-data:

networks:
  social-kit-network:
    driver: bridge
