// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://tmghqmwcavwyyoekppdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZ2hxbXdjYXZ3eXlvZWtwcGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjkwNjksImV4cCI6MjA3MTIwNTA2OX0.ObRc6kXInXeQEGlvSwyr6HZ3TkI--pLQMLIDxvWSuj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
